# Validates the byte-level contract for a plugin's static distribution documents. This file is
# both included by pvdkit-plugin.cmake at configure time and run directly by each package-docs
# CTest entry against the staged copies.
function(pvdkit_check_package_docs)
  cmake_parse_arguments(PARSE_ARGV 0 arg "" "PACKAGE_DIR;NAME;VERSION;CONTEXT" "")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "pvdkit_check_package_docs: unexpected arguments ${arg_UNPARSED_ARGUMENTS}")
  endif()
  foreach(required PACKAGE_DIR NAME VERSION)
    if(NOT DEFINED arg_${required} OR arg_${required} STREQUAL "")
      message(FATAL_ERROR "pvdkit_check_package_docs: ${required} is required")
    endif()
  endforeach()
  if(NOT arg_CONTEXT)
    set(arg_CONTEXT "pvdkit_package_docs(${arg_NAME})")
  endif()

  foreach(document readme_en.txt readme_ru.txt ChangeLog)
    set(path "${arg_PACKAGE_DIR}/${document}")
    if(NOT EXISTS "${path}" OR IS_DIRECTORY "${path}")
      message(FATAL_ERROR "${arg_CONTEXT}: required package document '${path}' does not exist")
    endif()
    file(READ "${path}" ${document}_hex HEX)
    string(TOLOWER "${${document}_hex}" ${document}_hex)
  endforeach()

  string(LENGTH "${readme_en.txt_hex}" english_hex_length)
  if(english_hex_length GREATER 0)
    math(EXPR english_last_byte "${english_hex_length} - 2")
    foreach(offset RANGE 0 ${english_last_byte} 2)
      string(SUBSTRING "${readme_en.txt_hex}" ${offset} 2 byte)
      math(EXPR byte_value "0x${byte}")
      if(NOT byte STREQUAL "09" AND NOT byte STREQUAL "0a" AND NOT byte STREQUAL "0d"
         AND (byte_value LESS 32 OR byte_value GREATER 126))
        math(EXPR byte_offset "${offset} / 2")
        message(
          FATAL_ERROR
            "${arg_CONTEXT}: readme_en.txt contains disallowed byte 0x${byte} at byte offset ${byte_offset}; "
            "only TAB, CR, LF and ASCII bytes 0x20-0x7E are allowed")
      endif()
    endforeach()
  endif()

  foreach(document readme_en.txt readme_ru.txt ChangeLog)
    set(document_hex "${${document}_hex}")
    string(LENGTH "${document_hex}" document_hex_length)
    if(document STREQUAL "readme_en.txt")
      set(first_content_offset 0)
      if(document_hex_length LESS 4)
        message(FATAL_ERROR "${arg_CONTEXT}: ${document} must contain at least one CRLF-terminated line")
      endif()
    else()
      set(first_content_offset 6)
      if(document_hex_length LESS 6)
        set(bom "")
      else()
        string(SUBSTRING "${document_hex}" 0 6 bom)
      endif()
      if(NOT bom STREQUAL "efbbbf")
        message(FATAL_ERROR "${arg_CONTEXT}: ${document} must start with the UTF-8 BOM (EF BB BF)")
      endif()
      if(document_hex_length LESS 10)
        message(FATAL_ERROR "${arg_CONTEXT}: ${document} must contain at least one CRLF-terminated line")
      endif()
    endif()

    math(EXPR document_last_byte "${document_hex_length} - 2")
    foreach(offset RANGE ${first_content_offset} ${document_last_byte} 2)
      string(SUBSTRING "${document_hex}" ${offset} 2 byte)
      if(byte STREQUAL "0d")
        math(EXPR neighbour_offset "${offset} + 2")
        if(neighbour_offset GREATER_EQUAL document_hex_length)
          message(FATAL_ERROR "${arg_CONTEXT}: every line in ${document} must end with CRLF")
        endif()
        string(SUBSTRING "${document_hex}" ${neighbour_offset} 2 neighbour)
        if(NOT neighbour STREQUAL "0a")
          message(FATAL_ERROR "${arg_CONTEXT}: every line in ${document} must end with CRLF")
        endif()
      elseif(byte STREQUAL "0a")
        if(offset EQUAL first_content_offset)
          message(FATAL_ERROR "${arg_CONTEXT}: every line in ${document} must end with CRLF")
        endif()
        math(EXPR neighbour_offset "${offset} - 2")
        string(SUBSTRING "${document_hex}" ${neighbour_offset} 2 neighbour)
        if(NOT neighbour STREQUAL "0d")
          message(FATAL_ERROR "${arg_CONTEXT}: every line in ${document} must end with CRLF")
        endif()
      endif()
    endforeach()
    math(EXPR final_crlf_offset "${document_hex_length} - 4")
    string(SUBSTRING "${document_hex}" ${final_crlf_offset} 4 final_crlf)
    if(NOT final_crlf STREQUAL "0d0a")
      message(FATAL_ERROR "${arg_CONTEXT}: the final line in ${document} must end with CRLF")
    endif()
  endforeach()

  set(changelog_first_line "")
  string(LENGTH "${ChangeLog_hex}" changelog_hex_length)
  math(EXPR changelog_last_byte "${changelog_hex_length} - 2")
  foreach(offset RANGE 6 ${changelog_last_byte} 2)
    string(SUBSTRING "${ChangeLog_hex}" ${offset} 2 byte)
    if(byte STREQUAL "0d")
      break()
    endif()
    math(EXPR byte_value "0x${byte}")
    string(ASCII ${byte_value} character)
    string(APPEND changelog_first_line "${character}")
  endforeach()
  string(REPLACE "." "\\." version_regex "${arg_VERSION}")
  if(NOT changelog_first_line MATCHES
     "^${arg_NAME} ${version_regex} [0-9][0-9]\\.[0-9][0-9]\\.[0-9][0-9][0-9][0-9]$")
    message(
      FATAL_ERROR
        "${arg_CONTEXT}: ChangeLog first line must be exactly '${arg_NAME} ${arg_VERSION} DD.MM.YYYY'; "
        "got '${changelog_first_line}'")
  endif()
endfunction()

if(DEFINED CMAKE_SCRIPT_MODE_FILE AND CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  pvdkit_check_package_docs(
    PACKAGE_DIR "${PVDKIT_PACKAGE_DIR}"
    NAME "${PVDKIT_PLUGIN_NAME}"
    VERSION "${PVDKIT_PLUGIN_VERSION}")
endif()
